import type { Metadata } from "next";
// Removed next/font imports to disable optimization
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

// Removed font loading configuration
// const geistSans = Geist({ ... });
// const geistMono = Geist_Mono({ ... });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Add suppressHydrationWarning if needed due to theme/class changes
    <html lang="en" suppressHydrationWarning>
      <body
        // Combine font variables using cn utility
        // Removed font variables from className, rely on Tailwind defaults or globals.css
        className={cn(
          "min-h-screen bg-background font-sans antialiased"
        )}
      >
        {children}
      </body>
    </html>
  );
}
