import type { Metadata } from "next";
// Removed Red_Hat_Display import
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Removed Red Hat Display configuration

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Add suppressHydrationWarning if needed due to theme/class changes
    <html lang="en" suppressHydrationWarning>
      <body
        // Combine font variables using cn utility
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          geistSans.variable,
          geistMono.variable
          // Removed redHatDisplay.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
